config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users, except: [:edit, :update]
  resources :posts, except: [:edit, :update]
  resources :comments, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, as: :commentable
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, as: :commentable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    Comment.create(comment_params)
    redirect_to root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :commentable_type, :commentable_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :destroy]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.new(post_params)
    if post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:text)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :destroy]

  def index
    @users = User.all
  end

  def show
    @comment = @user.comments.new
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      redirect_to user
    else
      render :new
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:login)
  end

  def find_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Polimorphic</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.haml
%h1 Posts
%table
  %tr
    %th Post
    %th Comments count
    %th{:colspan => "2"}
  - @posts.each do |post|
    %tr
      %td= post.text
      %td= post.comments.count
      %td= link_to 'Show', post
      %td= link_to 'Delete', post, method: :delete
%p
  = link_to "New Post", new_post_path 

app/views/posts/new.haml
%p
  = link_to 'Back', posts_path
%h1 New post
= form_for @post do |f|
  %p= f.text_area :text
  %p= f.submit 'Create post'

app/views/posts/show.haml
%p
  = link_to 'Back', posts_path
%h1
  Post #{@post.id}
%p
  Text: #{@post.text}
%h2 Add comment
= form_for @post.comments.new do |f|
  = f.hidden_field :commentable_type, value: 'Post'
  = f.hidden_field :commentable_id, value: @post.id
  = f.text_area :text
  = f.submit 'Save'
%h2 Comments
%table
  - @post.comments.each do |comment|
    %tr
      %p
        = comment.text

app/views/users/index.haml
%h3 Users
%table
  %tr
    %th User |
    %th Comments count
  - @users.each do |user|
    %tr
      %td 
        = user.login 
      %td 
        = user.comments.count
      %td 
        = link_to 'Show', user
        = link_to 'Delete', user, method: :delete
%p
  = link_to "Create user", new_user_path
  = link_to "Create post", new_post_path

app/views/users/new.haml
%h1
  New User
= form_for @user do |f|
  %p
    = f.label :login
  %p
    = f.text_field :login, placeholder: "Write user login"
  %p
    = f.submit "Create user"

app/views/users/show.haml
%p= link_to 'Back', users_path
%h3 User #{@user.id}
%p
  User: #{@user.login}
%h3 Add comment
= form_for @user.comments.new do |f|
  %p
    = f.text_area :text, placeholder: "Write a comment text"
    = f.hidden_field :commentable_type, value: "User"
    = f.hidden_field :commentable_id, value:  @user.id
  %p
    = f.submit 'Save'
%h3 Comments
%table
  - @user.comments.each do |comment|
    %tr
      %p
        = comment.text